export const AD_LOGIN_APP = 'AD_LOGIN_APP';
export const AD_LOGIN_SUC = 'AD_LOGIN_SUC';
export const AD_LOGIN_FAIL = 'AD_LOGIN_FAIL';
export const AD_REGISTRATION = 'AD_REGISTRATION';
export const AD_REGISTRATION_SUC = 'AD_REGISTRATION_SUC';
export const AD_REGISTRATION_FAIL = 'AD_REGISTRATION_FAIL';
