# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# trigger 

trigger: 
 - master


pool:
    vmImage: windows-2019

stages:
 - stage: Build
   jobs:
   - job: Build

     steps:
      - checkout: self
        clean: true
        fetchTags: false
        

      - task: UseDotNet@2
        inputs:
         packageType: 'sdk'
         version: '6.x'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: 'EcotimeMobileAPI.csproj'
          feedsToUse: 'select'
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          zipAfterPublish: false
        
      - task: CmdLine@2
        inputs:
         script: 'pwd && dir'
    
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'D:\a\1\s\bin\Debug\net6.0\publish'
          Contents: |
            **
            !**/web.config
            !**/appsettings.Development.json
            !**/appsettings.json
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'